### ISSUE TITLE
lmdb地址怎么还是作者的文件地址

### ISSUE THREAD

**Issue by brisker** [SHUCV/digit#6]
错误如下：
[  FAILED  ] 13 tests, listed below:
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/0.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/0.TestGradient, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/1.TestGradient, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/1.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/2.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/2.TestGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/3.TestGradient, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/3.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] LayerFactoryTest/2.TestCreateLayer, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] LayerFactoryTest/3.TestCreateLayer, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] NetUpgradeTest.TestUpgradeV1LayerType

13 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS
网上查了很多，解决不了。不知道作者有什么建议啊？
我没用cudnn，cuda是7.5

**Comment by brisker** [comment]
make all 与 make test 均已通过，跳过make runtest，执行convert.py后，执行solve.py ，也报错

**Comment by zeakey** [comment]
@brisker hi 你好. 欢迎你对本项目的关注. `make runtest`出错这个我经常遇到, 这可能不是个例. 我比较关注你执行`solve.py`后的错误, 因为这个关系到代码的可用性, 你能把执行`solve.py`报出来的错误的具体情况讲一下吗?

**Comment by brisker** [comment]
@zeakey 
运行solve.py后的错误：
I0804 18:39:41.742691 18213 layer_factory.hpp:76] Creating layer data
I0804 18:39:41.743238 18213 net.cpp:111] Creating Layer data
I0804 18:39:41.743263 18213 net.cpp:434] data -> data
F0804 18:39:41.744626 18239 db_lmdb.hpp:13] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
运行test_fcn11_full.m后错误：
Invalid MEX-file ‘/digit-master/matlab/+caffe/private/caffe_.mexa64': libhdf5_hl.so.10:
无法打开共享对象文件: 没有那个文件或目录

**Comment by brisker** [comment]
@zeakey   原因是你们的fcn11.prototxt里的lmdb路径没改过来。。。。。。。。。。。。。。。。

**Comment by brisker** [comment]
@zeakey   再请教一下，caffe.set_mode_gpu()
caffe.set_device(0,1)   我有多块gpu，为什么写成caffe.set_device(0,1)  报错啊？那怎么设置啊？

**Comment by shudct** [comment]
@brisker OH no, as far as my knowledge, caffe doesn't support multi-gpu through python interface.
multi-gpu training is only supported in Command-Line interface. If you really want to train your net on dual gpus, the solution is to set the deconv-layer parameters using pythin interface and save model, then finetune that model with command-line, with `--gpu all` option.
